Populate form values
Firesphere/silverstripe-partial-userforms pull request #17
Opened 2019-08-22 08:53 UTC by lhalaa

This change includes the following:
- Move submission to a separate controller
- Update composer
- Move template to namespaced location
- Remove deprecated `Member::currentUser()`
- Disable canCreate for field and form submissions
- Update tests

2019-08-22 23:02 UTC, Firesphere requested changes

2019-08-22 23:02 UTC, Firesphere commented on src/controllers/PartialUserFormController.php
> +                    ])->renderWith(['Firesphere\PartialUserforms\PartialUserForm', 'Page']);
You should be able to use `PartialUserForm::class, Page::class` here

2019-08-22 23:02 UTC, Firesphere commented on src/controllers/PartialUserFormController.php
> +            ])->renderWith(['Firesphere\PartialUserforms\PartialUserForm', 'Page']);
Same as above :)

2019-08-22 23:02 UTC, Firesphere commented on src/models/PartialFormSubmission.php
> +            foreach ($this->PartialFields() as $field) {
Could you use `$this->PartialFields()->map('Name', 'Value')->toArray()` here?

2019-08-23 02:41 UTC, lhalaa commented on src/controllers/PartialUserFormController.php
> +                    ])->renderWith(['Firesphere\PartialUserforms\PartialUserForm', 'Page']);
We don't have `PartialUserForm::class` so I used the controller class instead

2019-08-23 03:29 UTC, Firesphere commented on src/controllers/PartialUserFormController.php
> +            ])->renderWith([static::class, Page::class]);
👍

2019-08-23 03:32 UTC, Firesphere approved these changes

2019-08-23 03:32 UTC, merged